project:
  type: website

website:
  title:
    GTK LLM Chat
  #margin-footer: |
  #  {{< react Sidebar >}}
  favicon: images/org.fuentelibre.gtk_llm_Chat-bw.png
  twitter-card: true
  navbar:
    logo: images/animated_icon.gif
    toggle-position: right
    right:
      - href: index.qmd
        text: Home
      - href: downloads.qmd
        text: Downloads
      - href: documentation.qmd
        text: Documentation
      - href: development.qmd
        text: Development

format:
  html:
    theme: darkly
    resources:
      - images/*
    css: 
      - styles.css
    toc: false 
    include-after-body: 
      - text: <script type=module src="main.js" defer></script>
    body-classes: "dark-theme"


