project:
  type: website

website:
  title:
    GTK LLM Chat
  margin-footer: |
    {{< react Sidebar >}}
  favicon: images/org.fuentelibre.gtk_llm_Chat-bw.png
  twitter-card: true
  navbar:
    logo: images/animated_icon.gif
    right:
      - href: index.qmd
        text: About
      - about.qmd

format:
  html:
    theme: darkly
    css: 
      - styles.css
    toc: true
    include-after-body: 
      - text: <script type=module src="main.js" defer></script>
    body-classes: "dark-theme"


