project:
  type: website

website:
  title: "Gtk LLM Chat"
  favicon: images/org.fuentelibre.gtk_llm_Chat-bw.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: darkly
    css: 
      - node_modules/adwavecss/dist/styles.css
      - styles.css
    toc: true
    include-after-body: 
      - text: <script type=module src="node_modules/adwavecss/dist/index.js" defer></script>
      - text: <script type=module src="node_modules/adwaveui/dist/bundle/index.js" defer></script>
    body-classes: "dark-theme"


