project:
  type: website

website:
  title:
    Gtk LLM Chat
  favicon: images/org.fuentelibre.gtk_llm_Chat-bw.png
  twitter-card: true
  announcement: 
    icon: info-circle
    dismissable: true
    type: info
    content: |
      **Beta**: Gtk-LLM-Chat is Libre Software. While generally stable for daily use, it is provided "as-is" with no warranties.
    position: below-navbar
  navbar:
    logo: images/animated_icon.gif
    toggle-position: right
    right:
      - href: index.qmd
        text: Home
      - href: features.qmd
        text: Features
      - href: downloads.qmd
        text: Downloads
      - href: development.qmd
        text: Development

format:
  html:
    theme: darkly
    resources:
      - images/*
    css: 
      - styles.css
    toc: false 
    include-after-body: 
      - text: <script type=module src="main.js" defer></script>
    body-classes: "dark-theme"


