project:
  type: website

website:
  title:
    Gtk LLM Chat
  favicon: images/org.fuentelibre.gtk_llm_Chat-bw.png
  twitter-card: true
  announcement: 
    icon: party-popper
    dismissable: true
    type: primary # Or 'success' if you prefer
    content: |
      **New Release!** Gtk-LLM-Chat v4.0.4 is out! Check the [downloads page](/downloads.qmd) for the latest version. 🎉
    position: below-navbar
  navbar:
    logo: images/animated_icon.gif
    toggle-position: right
    right:
      - href: index.qmd
        text: Home
      - href: features.qmd
        text: Features
      - href: downloads.qmd
        text: Downloads
      - href: development.qmd
        text: Development

format:
  html:
    theme: darkly
    resources:
      - images/*
    css: 
      - styles.css
    toc: false 
    include-after-body: 
      - text: <script type=module src="main.js" defer></script>
    body-classes: "dark-theme"
